export interface CID10Entry {
  code: string;
  description: string;
  chapter: string;
}

export const CID10_TABLE: CID10Entry[] = [
  { code: 'A00', description: 'Colera', chapter: 'I' },
  { code: 'A01', description: 'Febres tifoides e paratifoides', chapter: 'I' },
  { code: 'A09', description: 'Diarreia e gastroenterite de origem infecciosa', chapter: 'I' },
  { code: 'A15', description: 'Tuberculose respiratoria', chapter: 'I' },
  { code: 'A16', description: 'Tuberculose das vias respiratorias', chapter: 'I' },
  { code: 'A41', description: 'Sepse', chapter: 'I' },
  { code: 'A50', description: 'Sifilis congenita', chapter: 'I' },
  { code: 'A64', description: 'Doenca sexualmente transmissivel', chapter: 'I' },
  { code: 'A87', description: 'Meningite meningococica', chapter: 'I' },
  { code: 'A90', description: 'Dengue classico', chapter: 'I' },
  { code: 'A91', description: 'Dengue hemorragico', chapter: 'I' },
  { code: 'A95', description: 'Febre amarela', chapter: 'I' },
  { code: 'A97', description: 'Dengue', chapter: 'I' },
  { code: 'C15', description: 'Neoplasia maligna do esofago', chapter: 'II' },
  { code: 'C16', description: 'Neoplasia maligna do estomago', chapter: 'II' },
  { code: 'C18', description: 'Neoplasia maligna do colon', chapter: 'II' },
  { code: 'C34', description: 'Neoplasia maligna dos bronquios e pulmoes', chapter: 'II' },
  { code: 'C50', description: 'Neoplasia maligna da mama', chapter: 'II' },
  { code: 'C53', description: 'Neoplasia maligna do colo do utero', chapter: 'II' },
  { code: 'C56', description: 'Neoplasia maligna do ovario', chapter: 'II' },
  { code: 'C61', description: 'Neoplasia maligna da prostata', chapter: 'II' },
  { code: 'C71', description: 'Neoplasia maligna do encefalo', chapter: 'II' },
  { code: 'C80', description: 'Neoplasia maligna sem localizacao especificada', chapter: 'II' },
  { code: 'D50', description: 'Anemia por deficiencia de ferro', chapter: 'III' },
  { code: 'D56', description: 'Talassemia', chapter: 'III' },
  { code: 'D57', description: 'Transtornos falciformes', chapter: 'III' },
  { code: 'D64', description: 'Outras anemias', chapter: 'III' },
  { code: 'D69', description: 'Purpura e outras afeccoes hemorragicas', chapter: 'III' },
  { code: 'E03', description: 'Outros hipotireoidismos', chapter: 'IV' },
  { code: 'E05', description: 'Tireotoxicose [hipertireoidismo]', chapter: 'IV' },
  { code: 'E10', description: 'Diabetes mellitus tipo 1', chapter: 'IV' },
  { code: 'E11', description: 'Diabetes mellitus tipo 2', chapter: 'IV' },
  { code: 'E14', description: 'Diabetes mellitus nao especificado', chapter: 'IV' },
  { code: 'E46', description: 'Desnutricao proteico-calorica nao especificada', chapter: 'IV' },
  { code: 'E66', description: 'Obesidade', chapter: 'IV' },
  { code: 'E78', description: 'Transtornos do metabolismo de lipoproteinas', chapter: 'IV' },
  { code: 'F10', description: 'Transtornos devidos ao uso de alcool', chapter: 'V' },
  { code: 'F20', description: 'Esquizofrenia', chapter: 'V' },
  { code: 'F31', description: 'Transtorno afetivo bipolar', chapter: 'V' },
  { code: 'F32', description: 'Episodios depressivos', chapter: 'V' },
  { code: 'F33', description: 'Transtorno depressivo recorrente', chapter: 'V' },
  { code: 'F41', description: 'Outros transtornos ansiosos', chapter: 'V' },
  { code: 'F41.0', description: 'Transtorno de panico', chapter: 'V' },
  { code: 'F41.1', description: 'Ansiedade generalizada', chapter: 'V' },
  { code: 'F45', description: 'Transtornos somatoformes', chapter: 'V' },
  { code: 'G20', description: 'Doenca de Parkinson', chapter: 'VI' },
  { code: 'G40', description: 'Epilepsia', chapter: 'VI' },
  { code: 'G43', description: 'Enxaqueca [migranea]', chapter: 'VI' },
  { code: 'G45', description: 'Acidente isquemico transitorio', chapter: 'VI' },
  { code: 'G46', description: 'Sindromes vasculares cerebrais', chapter: 'VI' },
  { code: 'G47', description: 'Transtornos do sono', chapter: 'VI' },
  { code: 'G56', description: 'Mononeuropatias dos membros superiores', chapter: 'VI' },
  { code: 'G80', description: 'Paralisia cerebral', chapter: 'VI' },
  { code: 'G81', description: 'Hemiplegia', chapter: 'VI' },
  { code: 'H10', description: 'Conjuntivite', chapter: 'VII' },
  { code: 'H25', description: 'Catarata senil', chapter: 'VII' },
  { code: 'H40', description: 'Glaucoma', chapter: 'VII' },
  { code: 'H54', description: 'Cegueira e visao subnormal', chapter: 'VII' },
  { code: 'H60', description: 'Otite externa', chapter: 'VIII' },
  { code: 'H66', description: 'Otite media supurativa', chapter: 'VIII' },
  { code: 'H90', description: 'Perda de audicao', chapter: 'VIII' },
  { code: 'I00', description: 'Febre reumatica', chapter: 'IX' },
  { code: 'I10', description: 'Hipertensao essencial (primaria)', chapter: 'IX' },
  { code: 'I11', description: 'Doenca cardiaca hipertensiva', chapter: 'IX' },
  { code: 'I20', description: 'Angina pectoris', chapter: 'IX' },
  { code: 'I21', description: 'Infarto agudo do miocardio', chapter: 'IX' },
  { code: 'I25', description: 'Doenca isquemica cronica do coracao', chapter: 'IX' },
  { code: 'I26', description: 'Embolia pulmonar', chapter: 'IX' },
  { code: 'I42', description: 'Miocardiopatia', chapter: 'IX' },
  { code: 'I46', description: 'Parada cardiaca', chapter: 'IX' },
  { code: 'I47', description: 'Taquicardia paroxistica', chapter: 'IX' },
  { code: 'I48', description: 'Fibrilacao e flutter atrial', chapter: 'IX' },
  { code: 'I49', description: 'Outras arritmias cardiacas', chapter: 'IX' },
  { code: 'I50', description: 'Insuficiencia cardiaca', chapter: 'IX' },
  { code: 'I61', description: 'Hemorragia intracerebral', chapter: 'IX' },
  { code: 'I63', description: 'Infarto cerebral', chapter: 'IX' },
  { code: 'I64', description: 'Acidente vascular cerebral, nao especificado', chapter: 'IX' },
  { code: 'I70', description: 'Aterosclerose', chapter: 'IX' },
  { code: 'I84', description: 'Hemorroidas', chapter: 'IX' },
  { code: 'J00', description: 'Resfriado comum', chapter: 'X' },
  { code: 'J02', description: 'Faringite aguda', chapter: 'X' },
  { code: 'J03', description: 'Amigdalite aguda', chapter: 'X' },
  { code: 'J04', description: 'Laringite e traqueite agudas', chapter: 'X' },
  { code: 'J06', description: 'Infeccoes agudas das vias aereas superiores', chapter: 'X' },
  { code: 'J06.9', description: 'Infeccao aguda das vias aereas superiores nao especificada', chapter: 'X' },
  { code: 'J10', description: 'Influenza devida a outro virus identificado', chapter: 'X' },
  { code: 'J11', description: 'Influenza [gripe], virus nao identificado', chapter: 'X' },
  { code: 'J12', description: 'Pneumonia viral', chapter: 'X' },
  { code: 'J13', description: 'Pneumonia devida a Streptococcus pneumoniae', chapter: 'X' },
  { code: 'J15', description: 'Pneumonia bacteriana', chapter: 'X' },
  { code: 'J18', description: 'Pneumonia por microorganismo nao especificado', chapter: 'X' },
  { code: 'J20', description: 'Bronquite aguda', chapter: 'X' },
  { code: 'J21', description: 'Bronquiolite aguda', chapter: 'X' },
  { code: 'J22', description: 'Infeccoes agudas das vias aereas inferiores', chapter: 'X' },
  { code: 'J30', description: 'Rinite alergica e vasomotora', chapter: 'X' },
  { code: 'J32', description: 'Sinusite cronica', chapter: 'X' },
  { code: 'J40', description: 'Bronquite nao especificada', chapter: 'X' },
  { code: 'J42', description: 'Bronquite cronica nao especificada', chapter: 'X' },
  { code: 'J43', description: 'Enfisema', chapter: 'X' },
  { code: 'J44', description: 'Doenca pulmonar obstrutiva cronica', chapter: 'X' },
  { code: 'J45', description: 'Asma', chapter: 'X' },
  { code: 'J46', description: 'Estado de mal asmatico', chapter: 'X' },
  { code: 'J47', description: 'Bronquiectasia', chapter: 'X' },
  { code: 'J96', description: 'Insuficiencia respiratoria', chapter: 'X' },
  { code: 'K21', description: 'Doenca de refluxo gastroesofagico', chapter: 'XI' },
  { code: 'K25', description: 'Ulcera gastrica', chapter: 'XI' },
  { code: 'K27', description: 'Ulcera peptica', chapter: 'XI' },
  { code: 'K29', description: 'Gastrite e duodenite', chapter: 'XI' },
  { code: 'K30', description: 'Dispepsia', chapter: 'XI' },
  { code: 'K35', description: 'Apendicite aguda', chapter: 'XI' },
  { code: 'K40', description: 'Hernia inguinal', chapter: 'XI' },
  { code: 'K52', description: 'Gastroenterite e colite nao infecciosas', chapter: 'XI' },
  { code: 'K58', description: 'Sindrome do intestino irritavel', chapter: 'XI' },
  { code: 'K72', description: 'Insuficiencia hepatica', chapter: 'XI' },
  { code: 'K74', description: 'Fibrose e cirrose hepatica', chapter: 'XI' },
  { code: 'K80', description: 'Colelitase', chapter: 'XI' },
  { code: 'K85', description: 'Pancreatite aguda', chapter: 'XI' },
  { code: 'L02', description: 'Abscesso cutaneo, furunculo e antraz', chapter: 'XII' },
  { code: 'L03', description: 'Celulite', chapter: 'XII' },
  { code: 'L20', description: 'Dermatite atopica', chapter: 'XII' },
  { code: 'L23', description: 'Dermatite alergica de contato', chapter: 'XII' },
  { code: 'L29', description: 'Prurido', chapter: 'XII' },
  { code: 'L30', description: 'Outras dermatites', chapter: 'XII' },
  { code: 'L40', description: 'Psoriase', chapter: 'XII' },
  { code: 'L50', description: 'Urticaria', chapter: 'XII' },
  { code: 'L70', description: 'Acne', chapter: 'XII' },
  { code: 'L97', description: 'Ulcera dos membros inferiores', chapter: 'XII' },
  { code: 'M05', description: 'Artrite reumatoide soropositiva', chapter: 'XIII' },
  { code: 'M06', description: 'Outras artrites reumatoides', chapter: 'XIII' },
  { code: 'M10', description: 'Gota', chapter: 'XIII' },
  { code: 'M15', description: 'Poliartrose', chapter: 'XIII' },
  { code: 'M16', description: 'Coxartrose', chapter: 'XIII' },
  { code: 'M17', description: 'Gonartrose', chapter: 'XIII' },
  { code: 'M19', description: 'Outras artroses', chapter: 'XIII' },
  { code: 'M23', description: 'Transtornos internos dos joelhos', chapter: 'XIII' },
  { code: 'M47', description: 'Espondilose', chapter: 'XIII' },
  { code: 'M50', description: 'Transtornos dos discos cervicais', chapter: 'XIII' },
  { code: 'M51', description: 'Transtornos de discos intervertebrais', chapter: 'XIII' },
  { code: 'M54', description: 'Dorsalgia', chapter: 'XIII' },
  { code: 'M75', description: 'Lesoes do ombro', chapter: 'XIII' },
  { code: 'M77', description: 'Outras entesopatias', chapter: 'XIII' },
  { code: 'M80', description: 'Osteoporose com fratura patologica', chapter: 'XIII' },
  { code: 'M81', description: 'Osteoporose sem fratura patologica', chapter: 'XIII' },
  { code: 'N10', description: 'Nefrite intersticial aguda', chapter: 'XIV' },
  { code: 'N17', description: 'Insuficiencia renal aguda', chapter: 'XIV' },
  { code: 'N18', description: 'Insuficiencia renal cronica', chapter: 'XIV' },
  { code: 'N19', description: 'Insuficiencia renal nao especificada', chapter: 'XIV' },
  { code: 'N20', description: 'Calculo do rim e do ureter', chapter: 'XIV' },
  { code: 'N30', description: 'Cistite', chapter: 'XIV' },
  { code: 'N39', description: 'Outros transtornos do sistema urinario', chapter: 'XIV' },
  { code: 'N40', description: 'Hiperplasia da prostata', chapter: 'XIV' },
  { code: 'N41', description: 'Doencas inflamatorias da prostata', chapter: 'XIV' },
  { code: 'N76', description: 'Inflamacao da vagina e da vulva', chapter: 'XIV' },
  { code: 'N92', description: 'Menstruacao excessiva, frequente ou irregular', chapter: 'XIV' },
  { code: 'N94', description: 'Dor e condicoes associadas com orgaos genitais femininos', chapter: 'XIV' },
  { code: 'N97', description: 'Infertilidade feminina', chapter: 'XIV' },
  { code: 'O00', description: 'Gravidez ectopica', chapter: 'XV' },
  { code: 'O24', description: 'Diabetes mellitus na gravidez', chapter: 'XV' },
  { code: 'O42', description: 'Ruptura prematura de membranas', chapter: 'XV' },
  { code: 'O60', description: 'Trabalho de parto prematuro', chapter: 'XV' },
  { code: 'O80', description: 'Parto unico espontaneo', chapter: 'XV' },
  { code: 'O82', description: 'Parto unico por cesariana', chapter: 'XV' },
  { code: 'P07', description: 'Transtornos relacionados com a prematuridade', chapter: 'XVI' },
  { code: 'P22', description: 'Sindrome de angustia respiratoria do recem-nascido', chapter: 'XVI' },
  { code: 'P28', description: 'Outras afeccoes respiratorias do periodo perinatal', chapter: 'XVI' },
  { code: 'P59', description: 'Ictericia neonatal devida a outras causas', chapter: 'XVI' },
  { code: 'Q00', description: 'Anencefalia', chapter: 'XVII' },
  { code: 'Q03', description: 'Hidrocefalia congenita', chapter: 'XVII' },
  { code: 'Q20', description: 'Malformacoes congenitas das cavidades cardiacas', chapter: 'XVII' },
  { code: 'Q21', description: 'Malformacoes congenitas dos septos cardiacos', chapter: 'XVII' },
  { code: 'Q53', description: 'Criptorquidia', chapter: 'XVII' },
  { code: 'Q90', description: 'Sindrome de Down', chapter: 'XVII' },
  { code: 'R00', description: 'Anormalidades dos batimentos cardiacos', chapter: 'XVIII' },
  { code: 'R03', description: 'Valores anormais de pressao arterial', chapter: 'XVIII' },
  { code: 'R05', description: 'Tosse', chapter: 'XVIII' },
  { code: 'R06', description: 'Anormalidades da respiracao', chapter: 'XVIII' },
  { code: 'R07', description: 'Dor de garganta e dor no peito', chapter: 'XVIII' },
  { code: 'R10', description: 'Dor abdominal e pelvica', chapter: 'XVIII' },
  { code: 'R11', description: 'Nausea e vomito', chapter: 'XVIII' },
  { code: 'R42', description: 'Tontura e instabilidade', chapter: 'XVIII' },
  { code: 'R50', description: 'Febre de outra origem e de origem desconhecida', chapter: 'XVIII' },
  { code: 'R51', description: 'Cefaleia', chapter: 'XVIII' },
  { code: 'R52', description: 'Dor nao classificada em outra parte', chapter: 'XVIII' },
  { code: 'R53', description: 'Mal-estar e fadiga', chapter: 'XVIII' },
  { code: 'R55', description: 'Sincope e colapso', chapter: 'XVIII' },
  { code: 'R56', description: 'Convulsoes nao classificadas em outra parte', chapter: 'XVIII' },
  { code: 'R63', description: 'Sintomas relativos a ingestao de alimentos e liquidos', chapter: 'XVIII' },
  { code: 'R69', description: 'Causas de morbidade nao especificadas', chapter: 'XVIII' },
  { code: 'S00', description: 'Traumatismo superficial da cabeca', chapter: 'XIX' },
  { code: 'S01', description: 'Ferimento da cabeca', chapter: 'XIX' },
  { code: 'S02', description: 'Fratura do cranio e dos ossos da face', chapter: 'XIX' },
  { code: 'S06', description: 'Traumatismo intracraniano', chapter: 'XIX' },
  { code: 'S12', description: 'Fratura do pescoco', chapter: 'XIX' },
  { code: 'S22', description: 'Fratura da costela, do esterno e da coluna toracica', chapter: 'XIX' },
  { code: 'S32', description: 'Fratura da coluna lombar e da pelve', chapter: 'XIX' },
  { code: 'S42', description: 'Fratura do ombro e do braco', chapter: 'XIX' },
  { code: 'S52', description: 'Fratura do antebraco', chapter: 'XIX' },
  { code: 'S62', description: 'Fratura ao nivel do punho e da mao', chapter: 'XIX' },
  { code: 'S72', description: 'Fratura do femur', chapter: 'XIX' },
  { code: 'S82', description: 'Fratura da perna', chapter: 'XIX' },
  { code: 'S92', description: 'Fratura do pe', chapter: 'XIX' },
  { code: 'T14', description: 'Traumatismo de localizacao nao especificada', chapter: 'XIX' },
  { code: 'V01', description: 'Pedestre traumatizado em colisao com bicicleta', chapter: 'XX' },
  { code: 'V03', description: 'Pedestre traumatizado em colisao com automovel', chapter: 'XX' },
  { code: 'V09', description: 'Pedestre traumatizado em acidente de transito', chapter: 'XX' },
  { code: 'V29', description: 'Motociclista traumatizado em acidente de transito', chapter: 'XX' },
  { code: 'V49', description: 'Ocupante de automovel traumatizado em acidente', chapter: 'XX' },
  { code: 'W00', description: 'Queda no mesmo nivel envolvendo gelo e neve', chapter: 'XX' },
  { code: 'W01', description: 'Queda no mesmo nivel por escorregao', chapter: 'XX' },
  { code: 'W10', description: 'Queda de escadas e degraus', chapter: 'XX' },
  { code: 'W19', description: 'Queda nao especificada', chapter: 'XX' },
  { code: 'W20', description: 'Atingido por objetos arremessados', chapter: 'XX' },
  { code: 'W50', description: 'Golpe ou mordedura desferido por outra pessoa', chapter: 'XX' },
  { code: 'W54', description: 'Mordedura ou golpe desferido por cao', chapter: 'XX' },
  { code: 'W55', description: 'Mordedura por outros animais', chapter: 'XX' },
  { code: 'W57', description: 'Picada de insetos e outros artropodes', chapter: 'XX' },
  { code: 'X00', description: 'Exposicao a fogo nao controlado', chapter: 'XX' },
  { code: 'X20', description: 'Contato com serpentes e lagartos venenosos', chapter: 'XX' },
  { code: 'X41', description: 'Envenenamento acidental por medicamentos', chapter: 'XX' },
  { code: 'X50', description: 'Excesso de esforco e movimentos repetitivos', chapter: 'XX' },
  { code: 'Y83', description: 'Ato cirurgico como causa de reacao anormal', chapter: 'XX' },
  { code: 'Z00', description: 'Exame geral de investigacao sem queixa', chapter: 'XXI' },
  { code: 'Z01', description: 'Outros exames especiais de pessoas sem queixa', chapter: 'XXI' },
  { code: 'Z02', description: 'Exame medico para fins administrativos', chapter: 'XXI' },
  { code: 'Z03', description: 'Observacao para suspeita de doencas afastadas', chapter: 'XXI' },
  { code: 'Z09', description: 'Exame de seguimento apos tratamento', chapter: 'XXI' },
  { code: 'Z12', description: 'Exame de rastreamento de neoplasias', chapter: 'XXI' },
  { code: 'Z21', description: 'Estado de infeccao assintomatica pelo HIV', chapter: 'XXI' },
  { code: 'Z23', description: 'Necessidade de imunizacao', chapter: 'XXI' },
  { code: 'Z29', description: 'Necessidade de outras medidas profilaticas', chapter: 'XXI' },
  { code: 'Z30', description: 'Anticoncepcao', chapter: 'XXI' },
  { code: 'Z33', description: 'Estado de gravidez', chapter: 'XXI' },
  { code: 'Z34', description: 'Supervisao de gravidez normal', chapter: 'XXI' },
  { code: 'Z35', description: 'Supervisao de gravidez de alto risco', chapter: 'XXI' },
  { code: 'Z36', description: 'Triagem prenatal', chapter: 'XXI' },
  { code: 'Z51', description: 'Outros cuidados medicos', chapter: 'XXI' },
];
